### ISSUE TITLE
启动打包，本应出现在assets 文件内的文件出现在dist 文件下

### ISSUE THREAD

**Issue by F1462900874** [webszy/vite-plugin-auto-zip#4]
### vite 配置
import { fileURLToPath, URL } from 'node:url'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import AutoImport from 'unplugin-auto-import/vite'
import Components from 'unplugin-vue-components/vite'
import { VantResolver } from '@vant/auto-import-resolver';
import AutoZip from 'vite-plugin-auto-zip'
// https://vitejs.dev/config/
export default defineConfig({
  server: {
    host: true,
    port: 6055,
    open: true
  },
  plugins: [
    vue(),
    // 自动导入依赖 API  https://github.com/antfu/unplugin-auto-import
    AutoImport({
      imports: ['vue', 'pinia', 'vue-router'],
      dirs: [
        'src/composables/**',
        'src/constants/**',
        'src/utils/**',
        'src/stores/**',
        'src/router/**'
      ],
      dts: true,
      resolvers: [],
    }),
    // Vue 按需自动导入组件  https://github.com/antfu/unplugin-vue-components
    Components({
      // 要搜索组件的目录的相对路径
      dirs: ['src/components'],
      // 组件的有效文件扩展名。
      extensions: ['vue'],
      resolvers: [VantResolver()],
      // 搜索子目录
      dts: true
    }),
    AutoZip()
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  build: {
    chunkSizeWarningLimit: 600,
    rollupOptions: {
      // https://rollupjs.org/guide/en/#outputmanualchunks
      output: {
        manualChunks(id) {
          if (id.includes('node_modules')) {
            return id.toString().split('node_modules/')[1].split('/')[0].toString();
          }
        }
      },
    },
  },
})
### package.json
{
"dependencies": {
    "axios": "1.6.5",
    "pinia": "^2.1.7",
    "vant": "4.8.2",
    "vite-plugin-auto-zip": "1.1.4",
    "vue": "^3.3.11",
    "vue-router": "^4.2.5",
  },
"devDependencies": {
    "@rushstack/eslint-patch": "^1.3.3",
    "@vant/auto-import-resolver": "1.0.2",
    "@vitejs/plugin-vue": "^4.5.2",
    "@vue/eslint-config-prettier": "^8.0.0",
    "eslint": "^8.49.0",
    "eslint-plugin-vue": "^9.17.0",
    "prettier": "^3.0.3",
    "unplugin-auto-import": "0.17.3",
    "unplugin-vue-components": "0.26.0",
    "vite": "^5.0.10"
  }
}

**Comment by webszy** [comment]
好的，我抽空检查下，感谢

**Comment by webszy** [comment]
already fix it on v1.2.0，also change the index of params, first params will be zip file name outputed. thanks for your message.
